sudo: true
language: rust
rust:
  - stable
  - beta
  - nightly

install:
  - wget http://libsdl.org/release/SDL2-2.0.5.tar.gz
  - tar -xzvf SDL2-2.0.5.tar.gz
  - pushd SDL2-2.0.5 && ./configure --prefix=/usr && make && sudo make install && popd
