sudo: false
dist: trusty
group: beta
language: rust
rust:
  - stable
  - beta
  - nightly

addons:
  apt:
    packages:
    - libsdl2-dev
    - libsdl2-image-dev
    - libsdl2-ttf-dev
    - libsdl2-mixer-dev
