sudo: false
language: rust
rust:
  - stable
  - beta
  - nightly

addons:
  apt:
    packages:
    - libibus-1.0-dev
    - libpulse-dev
    - libsdl2-dev
    - libsdl2-image-dev
    - libsdl2-ttf-dev
    - libsdl2-mixer-dev
    sources:
    - debian-sid
