[package]
name = "ggez"
description = "Rust library to create a Good Game Easily"
version = "0.2.1"
homepage = "http://ggez.rs"
repository = "https://github.com/ggez/ggez"
documentation = "https://docs.rs/ggez"
keywords = ["ggez", "graphics", "2D", "game", "engine"]
authors = [
   "Rafael Epplee <raffomania@gmail.com>",
   "Sven-Hendrik Haase <svenstaro@gmail.com>",
   "Simon Heath <icefoxen@gmail.com>",
]
license = "MIT"
readme = "README.md"
categories = ["game-engines"]

[lib]
name = "ggez"
path = "src/lib.rs"

[dependencies.sdl2]
version = "0.27"
default-features = false
features = ["image", "mixer"]

[dependencies]
sdl2-sys = "0.27"
rusttype = "0.2"
rand = "0.3"
zip = "0.1"
app_dirs = "1.1"
rodio = "0.4"
gfx = "0.13"
gfx_core = "0.5"
gfx_device_gl = "0.12"
gfx_window_sdl = "0.4"

rustc-serialize = "0.3"
toml = "0.2"
