[package]
name = "ggez"
description = "Rust library to create a Good Game Easily"
version = "0.2.1"
homepage = "http://ggez.rs"
repository = "https://github.com/ggez/ggez"
documentation = "https://docs.rs/ggez"
keywords = ["ggez", "graphics", "2D", "game", "engine"]
authors = [
   "Rafael Epplee <raffomania@gmail.com>",
   "Sven-Hendrik Haase <svenstaro@gmail.com>",
   "Simon Heath <icefoxen@gmail.com>",
]
license = "MIT"
readme = "README.md"
categories = ["game-engines"]

[lib]
name = "ggez"
path = "src/lib.rs"

[dependencies.sdl2]
version = "0.28"
default-features = false
features = ["image"]

[dependencies]
rusttype = "0.2"
rand = "0.3"
zip = "0.1"
app_dirs = "1.1"
gfx = "0.14"
gfx_device_gl = "0.13"
gfx_window_sdl = "0.5"
image = "0.12"
rodio = {git="https://github.com/tomaka/rodio.git", branch="master"}

rustc-serialize = "0.3"
toml = "0.2"
