[package]
name = "ggez"
description = "A lightweight game framework for making 2D games with minimum friction, inspired by Love2D."
version = "0.5.1"
homepage = "http://ggez.rs"
repository = "https://github.com/ggez/ggez"
documentation = "https://docs.rs/ggez"
keywords = ["ggez", "graphics", "2D", "game", "engine"]
authors = [
   "Rafael Epplee <raffomania@gmail.com>",
   "Sven-Hendrik Haase <svenstaro@gmail.com>",
   "Simon Heath <icefoxen@gmail.com>",
]

edition = "2018"
license = "MIT"
readme = "README.md"
categories = ["game-engines"]
build = "build.rs"
exclude = ["resources", "!DejaVuSerif.ttf"]

[badges]
maintenance = { status = "passively-maintained" }

[lib]
name = "ggez"
path = "src/lib.rs"

[profile.dev]
# Useful for making smaller wasm binaries
opt-level = "s"

[features]
default = ["c_dependencies"]
bzip2 = ["zip/bzip2"]
mp3 = ["rodio/mp3"]
multithread-image-decoding = ["image/hdr", "image/jpeg_rayon"]
c_dependencies = ["bzip2", "mp3"]

[workspace]
members = ["ggraphics", "gvfs"]

[dependencies]
ggraphics = { path = "ggraphics", version = "0.0.2" }
gvfs = { path = "gvfs", version = "0.1" }

bitflags = "1"
zip = { version = "0.5", default-features = false }
directories = "2"
glyph_brush = "0.6"
glutin = "0.22.0"
image = {version = "0.22", default-features = false, features = ["gif_codec", "jpeg", "ico", "png_codec", "pnm",
"tga", "tiff", "webp", "bmp", "dxt", ] }
rodio = { version = "0.10", default-features = false, features = ["flac", "vorbis", "wav"] }
serde = "1"
serde_derive = "1"
toml = "0.5"
log = "0.4"
lyon = "0.14"
smart-default = "0.5"
glam = {version = "0.8", features = ["mint"] }
# Has to be the same version of mint that our math lib uses here.
mint = "0.5"
gilrs = "0.7"
approx = "0.3"

[dev-dependencies]
chrono = "0.4"
fern = "0.5"
oorandom = "11"
structopt = "0.3"
cgmath = { version = "0.17", features = ["mint"]}
skeptic = "0.13"
getrandom = "0.1"
nalgebra = {version = "0.19", features = ["mint"] }

[build-dependencies]
skeptic = "0.13"

